services:
  application:
    container_name: javadev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysql: